name = "taxipulse-proxy"
main = "worker.js"
compatibility_date = "2025-01-01"
account_id = "00f0deafc674ef380e2e2963a8b0dda8"

[[kv_namespaces]]
binding = "TAXI_KV"
id = "587f2f1a5db3407ca9d3b7623abdf054"

# Cron Triggers :
#   - "0 5 * * *" : daily 5h UTC (= 6h Paris hiver / 7h été) -> aggregator QFAP events
#   - "0 6 * * 1" : lundi 6h UTC (= 7h Paris été / 8h hiver) -> récap fraîcheur Sheet
[triggers]
crons = ["0 5 * * *", "0 6 * * 1"]
